DROP TABLE attends CASCADE;
DROP TABLE taggedIn CASCADE;
DROP TABLE contains CASCADE;
DROP TABLE partOf CASCADE;
DROP TABLE livestream CASCADE;
DROP TABLE share CASCADE;
DROP TABLE receive CASCADE;
DROP TABLE post CASCADE;
DROP TABLE video CASCADE;
DROP TABLE event CASCADE;
DROP TABLE picture CASCADE;
DROP TABLE idea CASCADE;
DROP TABLE service CASCADE;
DROP TABLE friendList CASCADE;
DROP TABLE friendGroup CASCADE;
DROP TABLE circle CASCADE;
DROP TABLE interest CASCADE;
DROP TABLE email CASCADE;
DROP TABLE instantMessage CASCADE;
DROP TABLE message CASCADE;
DROP TABLE member CASCADE;








